export const AuctionAbi = [
  {
    inputs: [
      { internalType: "address", name: "_collectibleCast", type: "address" },
      { internalType: "address", name: "_usdc", type: "address" },
      { internalType: "address", name: "_treasury", type: "address" },
      { internalType: "address", name: "_owner", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AuctionAlreadyExists", type: "error" },
  { inputs: [], name: "AuctionNotActive", type: "error" },
  { inputs: [], name: "AuctionNotCancellable", type: "error" },
  { inputs: [], name: "AuctionNotEnded", type: "error" },
  { inputs: [], name: "DeadlineExpired", type: "error" },
  { inputs: [], name: "ECDSAInvalidSignature", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
    name: "ECDSAInvalidSignatureLength",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }],
    name: "ECDSAInvalidSignatureS",
    type: "error",
  },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  { inputs: [], name: "InvalidAddress", type: "error" },
  { inputs: [], name: "InvalidAuctionParams", type: "error" },
  { inputs: [], name: "InvalidBidAmount", type: "error" },
  { inputs: [], name: "InvalidCastHash", type: "error" },
  { inputs: [], name: "InvalidCreatorFid", type: "error" },
  { inputs: [], name: "InvalidShortString", type: "error" },
  { inputs: [], name: "NonceAlreadyUsed", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [{ internalType: "string", name: "str", type: "string" }],
    name: "StringTooLong",
    type: "error",
  },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "castHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "refundedBidder",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint96",
        name: "refundedBidderFid",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "address",
        name: "authorizer",
        type: "address",
      },
    ],
    name: "AuctionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          { internalType: "uint32", name: "minBidAmount", type: "uint32" },
          {
            internalType: "uint32",
            name: "minAuctionDuration",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxAuctionDuration",
            type: "uint32",
          },
          { internalType: "uint32", name: "maxExtension", type: "uint32" },
        ],
        indexed: false,
        internalType: "struct IAuction.AuctionConfig",
        name: "config",
        type: "tuple",
      },
    ],
    name: "AuctionConfigSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "castHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newEndTime",
        type: "uint256",
      },
    ],
    name: "AuctionExtended",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "castHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "refundTo",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "AuctionRecovered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "castHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint96",
        name: "winnerFid",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "AuctionSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "castHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint96",
        name: "creatorFid",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "endTime",
        type: "uint40",
      },
      {
        indexed: false,
        internalType: "address",
        name: "authorizer",
        type: "address",
      },
    ],
    name: "AuctionStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authorizer",
        type: "address",
      },
    ],
    name: "AuthorizerAllowed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "authorizer",
        type: "address",
      },
    ],
    name: "AuthorizerDenied",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "castHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "bidder",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint96",
        name: "bidderFid",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "authorizer",
        type: "address",
      },
    ],
    name: "BidPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "castHash",
        type: "bytes32",
      },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "BidRefunded",
    type: "event",
  },
  { anonymous: false, inputs: [], name: "EIP712DomainChanged", type: "event" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldTreasury",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newTreasury",
        type: "address",
      },
    ],
    name: "TreasurySet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "authorizer", type: "address" }],
    name: "allowAuthorizer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "castHash", type: "bytes32" }],
    name: "auctionState",
    outputs: [
      { internalType: "enum IAuction.AuctionState", name: "", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "castHash", type: "bytes32" }],
    name: "auctions",
    outputs: [
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "uint96", name: "creatorFid", type: "uint96" },
      { internalType: "address", name: "highestBidder", type: "address" },
      { internalType: "uint96", name: "highestBidderFid", type: "uint96" },
      { internalType: "uint256", name: "highestBid", type: "uint256" },
      { internalType: "uint40", name: "lastBidAt", type: "uint40" },
      { internalType: "uint40", name: "endTime", type: "uint40" },
      { internalType: "uint32", name: "bids", type: "uint32" },
      {
        internalType: "enum IAuction.AuctionState",
        name: "state",
        type: "uint8",
      },
      {
        components: [
          { internalType: "uint64", name: "minBid", type: "uint64" },
          {
            internalType: "uint16",
            name: "minBidIncrementBps",
            type: "uint16",
          },
          { internalType: "uint16", name: "protocolFeeBps", type: "uint16" },
          { internalType: "uint32", name: "duration", type: "uint32" },
          { internalType: "uint32", name: "extension", type: "uint32" },
          {
            internalType: "uint32",
            name: "extensionThreshold",
            type: "uint32",
          },
        ],
        internalType: "struct IAuction.AuctionParams",
        name: "params",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "signer", type: "address" }],
    name: "authorizers",
    outputs: [{ internalType: "bool", name: "authorized", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "castHashes", type: "bytes32[]" },
      {
        components: [
          { internalType: "bytes32", name: "nonce", type: "bytes32" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct IAuction.AuthData[]",
        name: "authDatas",
        type: "tuple[]",
      },
    ],
    name: "batchCancel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "castHashes", type: "bytes32[]" },
    ],
    name: "batchSettle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "castHash", type: "bytes32" },
      {
        components: [
          { internalType: "uint96", name: "bidderFid", type: "uint96" },
          { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        internalType: "struct IAuction.BidData",
        name: "bidData",
        type: "tuple",
      },
      {
        components: [
          { internalType: "bytes32", name: "nonce", type: "bytes32" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct IAuction.AuthData",
        name: "auth",
        type: "tuple",
      },
      {
        components: [
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "uint8", name: "v", type: "uint8" },
          { internalType: "bytes32", name: "r", type: "bytes32" },
          { internalType: "bytes32", name: "s", type: "bytes32" },
        ],
        internalType: "struct IAuction.PermitData",
        name: "permit",
        type: "tuple",
      },
    ],
    name: "bid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "castHash", type: "bytes32" },
      {
        components: [
          { internalType: "uint96", name: "bidderFid", type: "uint96" },
          { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        internalType: "struct IAuction.BidData",
        name: "bidData",
        type: "tuple",
      },
      {
        components: [
          { internalType: "bytes32", name: "nonce", type: "bytes32" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct IAuction.AuthData",
        name: "auth",
        type: "tuple",
      },
    ],
    name: "bid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "castHash", type: "bytes32" },
      {
        components: [
          { internalType: "bytes32", name: "nonce", type: "bytes32" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct IAuction.AuthData",
        name: "auth",
        type: "tuple",
      },
    ],
    name: "cancel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "collectible",
    outputs: [
      { internalType: "contract ICollectibleCasts", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "config",
    outputs: [
      { internalType: "uint32", name: "minBidAmount", type: "uint32" },
      { internalType: "uint32", name: "minAuctionDuration", type: "uint32" },
      { internalType: "uint32", name: "maxAuctionDuration", type: "uint32" },
      { internalType: "uint32", name: "maxExtension", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "authorizer", type: "address" }],
    name: "denyAuthorizer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { internalType: "bytes1", name: "fields", type: "bytes1" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "version", type: "string" },
      { internalType: "uint256", name: "chainId", type: "uint256" },
      { internalType: "address", name: "verifyingContract", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "uint256[]", name: "extensions", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "castHash", type: "bytes32" }],
    name: "getAuction",
    outputs: [
      {
        components: [
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "uint96", name: "creatorFid", type: "uint96" },
          { internalType: "address", name: "highestBidder", type: "address" },
          { internalType: "uint96", name: "highestBidderFid", type: "uint96" },
          { internalType: "uint256", name: "highestBid", type: "uint256" },
          { internalType: "uint40", name: "lastBidAt", type: "uint40" },
          { internalType: "uint40", name: "endTime", type: "uint40" },
          { internalType: "uint32", name: "bids", type: "uint32" },
          {
            internalType: "enum IAuction.AuctionState",
            name: "state",
            type: "uint8",
          },
          {
            components: [
              { internalType: "uint64", name: "minBid", type: "uint64" },
              {
                internalType: "uint16",
                name: "minBidIncrementBps",
                type: "uint16",
              },
              {
                internalType: "uint16",
                name: "protocolFeeBps",
                type: "uint16",
              },
              { internalType: "uint32", name: "duration", type: "uint32" },
              { internalType: "uint32", name: "extension", type: "uint32" },
              {
                internalType: "uint32",
                name: "extensionThreshold",
                type: "uint32",
              },
            ],
            internalType: "struct IAuction.AuctionParams",
            name: "params",
            type: "tuple",
          },
        ],
        internalType: "struct IAuction.AuctionData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "castHash", type: "bytes32" },
      { internalType: "address", name: "bidder", type: "address" },
      { internalType: "uint96", name: "bidderFid", type: "uint96" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bytes32", name: "nonce", type: "bytes32" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "hashBidAuthorization",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "castHash", type: "bytes32" },
      { internalType: "bytes32", name: "nonce", type: "bytes32" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "hashCancelAuthorization",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "castHash", type: "bytes32" },
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "uint96", name: "creatorFid", type: "uint96" },
      { internalType: "address", name: "bidder", type: "address" },
      { internalType: "uint96", name: "bidderFid", type: "uint96" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        components: [
          { internalType: "uint64", name: "minBid", type: "uint64" },
          {
            internalType: "uint16",
            name: "minBidIncrementBps",
            type: "uint16",
          },
          { internalType: "uint16", name: "protocolFeeBps", type: "uint16" },
          { internalType: "uint32", name: "duration", type: "uint32" },
          { internalType: "uint32", name: "extension", type: "uint32" },
          {
            internalType: "uint32",
            name: "extensionThreshold",
            type: "uint32",
          },
        ],
        internalType: "struct IAuction.AuctionParams",
        name: "params",
        type: "tuple",
      },
      { internalType: "bytes32", name: "nonce", type: "bytes32" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "hashStartAuthorization",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingOwner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "castHash", type: "bytes32" },
      { internalType: "address", name: "refundTo", type: "address" },
    ],
    name: "recover",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint32", name: "minBidAmount", type: "uint32" },
          {
            internalType: "uint32",
            name: "minAuctionDuration",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxAuctionDuration",
            type: "uint32",
          },
          { internalType: "uint32", name: "maxExtension", type: "uint32" },
        ],
        internalType: "struct IAuction.AuctionConfig",
        name: "_config",
        type: "tuple",
      },
    ],
    name: "setAuctionConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_treasury", type: "address" }],
    name: "setTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "castHash", type: "bytes32" }],
    name: "settle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes32", name: "castHash", type: "bytes32" },
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "uint96", name: "creatorFid", type: "uint96" },
        ],
        internalType: "struct IAuction.CastData",
        name: "cast",
        type: "tuple",
      },
      {
        components: [
          { internalType: "uint96", name: "bidderFid", type: "uint96" },
          { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        internalType: "struct IAuction.BidData",
        name: "bidData",
        type: "tuple",
      },
      {
        components: [
          { internalType: "uint64", name: "minBid", type: "uint64" },
          {
            internalType: "uint16",
            name: "minBidIncrementBps",
            type: "uint16",
          },
          { internalType: "uint16", name: "protocolFeeBps", type: "uint16" },
          { internalType: "uint32", name: "duration", type: "uint32" },
          { internalType: "uint32", name: "extension", type: "uint32" },
          {
            internalType: "uint32",
            name: "extensionThreshold",
            type: "uint32",
          },
        ],
        internalType: "struct IAuction.AuctionParams",
        name: "params",
        type: "tuple",
      },
      {
        components: [
          { internalType: "bytes32", name: "nonce", type: "bytes32" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct IAuction.AuthData",
        name: "auth",
        type: "tuple",
      },
      {
        components: [
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "uint8", name: "v", type: "uint8" },
          { internalType: "bytes32", name: "r", type: "bytes32" },
          { internalType: "bytes32", name: "s", type: "bytes32" },
        ],
        internalType: "struct IAuction.PermitData",
        name: "permit",
        type: "tuple",
      },
    ],
    name: "start",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes32", name: "castHash", type: "bytes32" },
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "uint96", name: "creatorFid", type: "uint96" },
        ],
        internalType: "struct IAuction.CastData",
        name: "cast",
        type: "tuple",
      },
      {
        components: [
          { internalType: "uint96", name: "bidderFid", type: "uint96" },
          { internalType: "uint256", name: "amount", type: "uint256" },
        ],
        internalType: "struct IAuction.BidData",
        name: "bidData",
        type: "tuple",
      },
      {
        components: [
          { internalType: "uint64", name: "minBid", type: "uint64" },
          {
            internalType: "uint16",
            name: "minBidIncrementBps",
            type: "uint16",
          },
          { internalType: "uint16", name: "protocolFeeBps", type: "uint16" },
          { internalType: "uint32", name: "duration", type: "uint32" },
          { internalType: "uint32", name: "extension", type: "uint32" },
          {
            internalType: "uint32",
            name: "extensionThreshold",
            type: "uint32",
          },
        ],
        internalType: "struct IAuction.AuctionParams",
        name: "params",
        type: "tuple",
      },
      {
        components: [
          { internalType: "bytes32", name: "nonce", type: "bytes32" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bytes", name: "signature", type: "bytes" },
        ],
        internalType: "struct IAuction.AuthData",
        name: "auth",
        type: "tuple",
      },
    ],
    name: "start",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdc",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "nonce", type: "bytes32" }],
    name: "usedNonces",
    outputs: [{ internalType: "bool", name: "used", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
